"""Create users table

Revision ID: 695d1e367c95
Revises: 
Create Date: 2022-02-01 10:12:31.618891

"""
import sqlalchemy as sa
from alembic import op
from core.config import settings
from db import users as DBUsers
from schemas.user import UserCreate
from sqlalchemy import orm

# revision identifiers, used by Alembic.
revision = '695d1e367c95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('users',
                            sa.Column('id', sa.Integer(), nullable=False),
                            sa.Column('email', sa.String(), nullable=True),
                            sa.Column('password', sa.String(), nullable=False),
                            sa.Column('is_active', sa.Boolean(),
                                      nullable=True),
                            sa.Column('is_superuser',
                                      sa.Boolean(), nullable=True),
                            sa.PrimaryKeyConstraint('id')
                            )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###

    # create default admin user with app rules
    DBUsers.create_user(
        db=orm.Session(bind=op.get_bind()),
        user=UserCreate(
            email=settings.ADMIN_EMAIL,
            password=settings.ADMIN_PASSWORD,
            is_active=True,
            is_superuser=True
        ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
