"""create users/projects table

Revision ID: 83267cc3af94
Revises: 
Create Date: 2022-02-06 22:49:42.556907

"""
import sqlalchemy as sa
from alembic import op
from core.config import settings
from db import users as DBUsers
from schemas.user import UserCreate
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = '83267cc3af94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('fullname', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('projects',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('private', sa.Boolean(), nullable=True),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'),
                    'projects', ['name'], unique=True)
    # ### end Alembic commands ###

# create default admin user with app rules
    DBUsers.create_user(
        db=Session(bind=op.get_bind()),
        user=UserCreate(
            email=settings.ADMIN_EMAIL,
            fullname="Admin user",
            password=settings.ADMIN_PASSWORD,
            is_active=True,
            is_superuser=True
        ))
    if settings.DEMO_EMAIL:
        DBUsers.create_user(
            db=Session(bind=op.get_bind()),
            user=UserCreate(
                email=settings.DEMO_EMAIL,
                fullname="Demo user",
                password=settings.DEMO_PASSWORD,
                is_active=True,
                is_superuser=False
            ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
